### PR TITLE
Update Cutechess binaries to v1.2.0 cutechess/cutechess@3d1ac5b7

### PR DESCRIPTION
**Pull request by ppigazzini**
Cutechess binaries built from v1.2.0 cutechess/cutechess@3d1ac5b7
using these [instructions](https://github.com/glinscott/fishtest/wiki/Build-cutechess-with-Qt5-static).

``` bash
$ git log --online -n 5
3d1ac5b7 bump windows installer to version 1.2.0
72a4e5de update the windows installer
4aa5d11f cutechess 1.2.0
788cab77 Fix the initial ply count for bare king in ASEAN and Sittuyin
a9e60884 link to 'Building from source' wiki page
```

All files tested clean with VirusTotal

[cutechess-cli-win.zip](https://www.virustotal.com/gui/file/0ef5f037c3569627e5e51233f4f77ec22bb8102d99669e217379c53e977ad4eb/detection)

[cutechess-cli-linux-64bit.zip](https://www.virustotal.com/gui/file/b82ca4f9c00c30cda41ff35c05a0c8c5c6b3121b5b10a46afa9b1cbc1475ce75/detection)

[cutechess-cli-linux-32bit.zip](https://www.virustotal.com/gui/file/fb885811046922d7992d151dd7359e0dd206bffe7592816ea9ba48eedc6cc4c7/detection)

### CODE REVIEW

**Comment by ppigazzini** [comment]
These new builds have been working fine for ten days on multi variant fishtest and on DEV (with my workers).

cutechess-cli v1.2.0 has updated the output:
```
Started game 19 of 20 (base vs test)
Finished game 19 (base vs test): 0-1 {Black wins by adjudication}
Score of base vs test: 4 - 10 - 5  [0.342] 19
...      base playing White: 3 - 4 - 3  [0.450] 10
...      base playing Black: 1 - 6 - 2  [0.222] 9
...      White vs Black: 9 - 5 - 5  [0.605] 19
Elo difference: -113.6 +/- 149.6, LOS: 5.4 %, DrawRatio: 26.3 %
Started game 20 of 20 (test vs base)
Finished game 20 (test vs base): 1/2-1/2 {Draw by adjudication}
Score of base vs test: 4 - 10 - 6  [0.350] 20
...      base playing White: 3 - 4 - 3  [0.450] 10
...      base playing Black: 1 - 6 - 3  [0.250] 10
...      White vs Black: 9 - 5 - 6  [0.600] 20
Elo difference: -107.5 +/- 139.5, LOS: 5.4 %, DrawRatio: 30.0 %
Finished match
```

previous cutechess-cli:
```
Started game 19 of 20 (base vs test)
Finished game 19 (base vs test): 0-1 {Black wins by adjudication}
Score of base vs test: 7 - 7 - 5  [0.500] 19
Elo difference: 0.0 +/- 141.2, LOS: 50.0 %, DrawRatio: 26.3 %
Started game 20 of 20 (test vs base)
Finished game 20 (test vs base): 1-0 {White wins by adjudication}
Score of base vs test: 7 - 8 - 5  [0.475] 20
Elo difference: -17.4 +/- 138.8, LOS: 39.8 %, DrawRatio: 25.0 %
Finished match
```

**Comment by vondele** [comment]
do we need to make changes to the worker to deal with this changed output ?

**Comment by ppigazzini** [comment]
IMO no, better to ask to @vdbergh too.

**Comment by vdbergh** [comment]
I'll have a look tonight.

**Comment by ppigazzini** [comment]
@vondele your PR https://github.com/cutechess/cutechess/pull/551 was merged, cutechess-cli version is raised, so IIRC we should be able to fix https://github.com/glinscott/fishtest/issues/478

**Comment by vondele** [comment]
yes, I agree we should be able to deal with https://github.com/glinscott/fishtest/issues/478 now. I know what needs to be done to the worker code, in principle, but this also requires passing some additional info from the server.. I'll see if I can figure this out.

**Comment by vondele** [comment]
I wait til @vdbergh confirms we can use this without changes, before I merge this PR.

**Comment by ppigazzini** [comment]
This is a low priority PR, useful only to work on glinscott/fishtest#478
Anyway my workers on DEV are already using the new cutechess-cli with:
```
git clone --single-branch --branch master https://github.com/glinscott/fishtest.git
cd ${test_folder}/fishtest
git config user.email "you@example.com"
git config user.name "your_name"

# add here the upstream branches to be tested
git remote add new-upstream https://github.com/ppigazzini/fishtest
git pull --no-edit new-upstream TEST_ppigazzini_books
```

**Comment by vondele** [comment]
@ppigazzini see
https://github.com/cutechess/cutechess/issues/616
I think standard chess is not affected, but I'm not 100% sure. (I've asked in the issue).

**Comment by ppigazzini** [comment]
@vondele subscribed, thank you.

**Pull request merged**
