### PR TITLE
Another book with unbalanced human openings

### PR DESCRIPTION
**Pull request by vondele**
A new book derived from Lichess games, with a model draw rate between 48% and 52%

It attempts to address the following points, relative to the currently used book:

* about 10x larger (2.6M pos), i.e. more variety while testing on fishtest, no repeated openings for any single test played.
* both white and black advantage around +- 1.0
* positions at all game plies between 1 and 16

The construction process involved

1) Parsing all 15B lichess games in the database https://database.lichess.org/ for the period Jan - Sept 2023.
   Extract from these the popular positions, i.e. seen at least twice, within the first 16 plies played, exploring newly added games to at most 8 previously unseen plies.
```
$ ./fastpopular --dir /mnt/md0/chess/lichessgames/2023/ --minCount 2 --stopEarly --countStopEarly 8 --maxPlies 16 --concurrency 9 -o popular_Lichess_JanSept_maxPlies16_stopEarly8.epd
Looking for pgn files in /mnt/md0/chess/lichessgames/2023/
Found 9 .pgn(.gz) files, creating 9 chunks for processing.
Processed 9 files
Retained 296993424 positions from 1127228493 unique visited in 15251265926 games.
Total time for processing: 7374.5 s
```
   fastpopular as available at https://github.com/vondele/fastpopular

2) Score all these 296M games with a modified stockfish, based on master, that analyses positions up to a depth 24, for as long as the draw rate is predicted (UCI_ShowWDL) near 50%.
   Positions will be analysed to low depth if the draw rate is very different from 50% at low depth.
   From these scored positions, extract those with a draw rate in the range 48 - 52%
   That modified branch is available at https://github.com/vondele/Stockfish/tree/createUHO
```
   ./stockfish.createUHO bench 128 1 24 popular_Lichess_JanSept_maxPlies16_stopEarly8.epd > popular_Lichess_JanSept_maxPlies16_stopEarly8_scored.epd
   awk '{if ($15>480 && $15<520) print $0}' popular_Lichess_JanSept_maxPlies16_stopEarly8_scored.epd | cut -d';' -f1 | sed "s/ $//g" > UHO_Lichess_4852_v1.epd
```

Short initial testing at STC shows the draw rate is, as expected, close to 50% for self-play games:
```
Score of master1 vs master2: 1048 - 1031 - 1921 [] 4000
Elo difference: 1.48 +/- 7.75, LOS: 64.54 %, DrawRatio: 48.02 %
Ptnml:        WW     WD  DD/WL     LD     LL
Distr:        21    473   1026    462     18
```

### CODE REVIEW

**Comment by robertnurnberg** [comment]
> * positions at all game plies between 1 and 16

Just a tiny correction. The earliest game ply I could find is 2, e.g. for the position `rnbqkbnr/p1pppppp/8/1p6/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 2`.

**Comment by robertnurnberg** [comment]
For future reference, the following positions have a superfluous ep square:
```
r1b1kb1r/pp2qppp/5n2/2ppP3/2B2Q2/8/PPP2PPP/RNB1K2R w KQkq d6 0 9
r1b1k1nr/ppp1qppp/2n5/3pP3/1b1P4/5N2/PP1B1PPP/RN1QKB1R w KQkq d6 0 8
rnb1kbnr/pp2qppp/2p5/3pP3/3Q4/5N2/PPP2PPP/RNB1KB1R w KQkq d6 0 6
r1b1kbnr/ppp2ppp/2n5/3q4/3PpP2/2P5/PP2Q1PP/RNB1KBNR b KQkq d3 0 6
rnb1kbnr/ppp1qp1p/8/3pP1p1/3P1p2/5N1P/PPP3P1/RNBQKB1R w KQkq d6 0 7
r1b1kbnr/ppp1qppp/2n5/3pP3/3P1B2/8/PPP3PP/RN1QKBNR w KQkq d6 0 6
rnbqk2r/ppp2ppp/3b1n2/3P4/2PPp3/1N6/PP2QPPP/RNB1KB1R b KQkq d3 0 8
r1b1kb1r/pp2qppp/5n2/2ppP3/2Bp1B2/3P1Q2/PPP2PPP/RN2K2R w KQkq d6 0 9
r1bqk2r/pppn1ppp/5n2/2bP4/2BPp3/4QP2/PPP3PP/RNB1K1NR b KQkq d3 0 7
rnb1kb1r/ppp2ppp/5n2/3q4/3Pp3/2P5/PP2QPPP/RNB1KBNR b KQkq d3 0 6
rnb1k2r/pp3ppp/3b1n2/2pq4/3Pp3/2P5/PPN1QPPP/RNB1KB1R b KQkq d3 0 8
rnb1k2r/ppp1qppp/8/3pP3/8/2P2N2/P1P2PPP/R2QKB1R w KQkq d6 0 9
rnb1k1nr/ppp1q1pp/8/2bpP3/2Bp4/5N2/PPP3PP/RNBQK2R w KQkq d6 0 8
r1b1k1nr/p1p1qppp/1pn5/2bpP3/5Q2/5N2/PPP2PPP/RNB1KB1R w KQkq d6 0 8
rnb1kbnr/pp2qp1p/2p5/3pP1p1/2QP1p2/2N2N2/PPP3PP/R1B1KB1R w KQkq d6 0 9
rnbqk1r1/ppp3pp/8/2bp1P2/3Pp3/5N2/PPP1QPPP/RNB1K2R b KQq d3 0 7
rnb1kb1r/ppp1qppp/5n2/3pP3/3P1p1P/8/PPP3P1/RNBQKBNR w KQkq d6 0 6
r1bqkb1r/pp3ppp/2n2n2/8/3PpP2/2P5/PP2Q1PP/RNB1KBNR b KQkq d3 0 7
rnbqk2r/pp3ppp/3b1n2/3p4/3Pp3/1B2Q2P/PPP2PP1/RNB1K1NR b KQkq d3 0 8
```

Nevertheless, even with those ep squares removed, all the positions in the book remain unique.

Observe that the FENs above will never appear in Fishtest PGNs, because fastchess will replace the ep squares with `-`.

**Comment by robertnurnberg** [comment]
The attached plot shows an analysis of all the single thread games played with this book that are part of the [Hugging Face Repo](https://huggingface.co/datasets/robertnurnberg/fishtest_pgns). We can observe a slight upward drift of the pair draw rate (and a small decline of the overall draw rate), indicating that as Stockfish gets stronger, more pairs get drawn (and possibly more pairs are "busted").

Overall, the observed draw rates are still excellent.

UHO_Lichess_4852_v1_d30

**Comment by FauziAkram** [comment]
@vondele In the pull description, it's mentioned "both white and black advantage around ±1.0".
Could you clarify what evaluation range was actually accepted when selecting positions?
Specifically, is it possible to know the minimum and maximum evaluation values that were used as cutoffs for inclusion in the book?

Thanks in advance for the clarification.

**Comment by robertnurnberg** [comment]
Draw rate from the wdl model between 48 and 52.

**Comment by FauziAkram** [comment]
@robertnurnberg Thanks for the clarification.
Is there a way to translate that draw rate range into a corresponding Stockfish evaluation range?
Roughly, what evaluation values would that draw-rate range map to?

**Comment by robertnurnberg** [comment]
A rough guess is [-0.97, 1.03]. But that will depend on the material count (for latest dev). This is the reason why working with the wdl numbers is better.

**Comment by robertnurnberg** [comment]
Here an update for the analysis from https://github.com/official-stockfish/books/pull/39#issuecomment-2832578978.
```
--- Aggregated Statistics ---
File Pattern  : **/*.json
Book Pattern  : UHO_Lichess_4852_v1.epd
Threads       : 1
Matched Files : 3751
W/D/L         : 107796421/210309044/107640761
Draw Rate     : 49.40%
Pentanomial   : 236843,46785909,118676769,46931929,241663
Pair Draw Rate: 55.75%
```
UHO_Lichess_4852_v1_d30

**Pull request merged**
