### PR TITLE
Book for closed positions

### PR DESCRIPTION
**Pull request by vondele**
extracted from LTC fishtest games based mostly on noob_3moves book,
using the position after 8 plies for those games where the position
after 12 plies. Being closed uses the 3 rules:
* pe->blocked_count() >= 4
* pos.count<ALL_PIECES>() >= 26
* go perft 5 < 40000000

Preliminary testing at STC between sf10 and sf11 yields

Score of sf10 vs sf11: 378 - 801 - 1573  [0.423] 2752
Elo difference: -53.8 +/- 8.4, LOS: 0.0 %, DrawRatio: 57.2 %

which is similar to noob_3moves book (~45 Elo) at these conditions.

contains 165735 positions.

### CODE REVIEW

**Comment by vondele** [comment]
@noobpwnftw I'll merge this in the official book repo and do some tests on fishtest later. Do you need to manually update your workers first?

**Comment by noobpwnftw** [comment]
@vondele No, I think my workers should be able to download small books without problem.

**Comment by snicolet** [comment]
> Being closed uses the 3 rules:

> • pe->blocked_count() >= 4
> • pos.count<ALL_PIECES>() >= 26
> • go perft 5 < 40000000

Is it an 'OR' or and 'AND' between the three conditions?

------------

I am asking, because I have been curious to look at some of the the games of my test called "22 * support (test with new "closedpos.epd" book)" there:
https://tests.stockfishchess.org/tests/view/5ea5386bb908f6dd28f34c41

I have downloaded the games of worker 5 (randomly choosing worker 5) in that test, which is this PGN file:

https://tests.stockfishchess.org/api/pgn/5ea5386bb908f6dd28f34c41-5.pgn
http://cassio.free.fr/divers/5ea5386bb908f6dd28f34c41-5.pgn

There are games in this PGN file with games without blocked pawns at all in the initial position (even with the relaxed definition of "blocked pawns" given in line 109 of pawns.cpp), for instance the first game start with:

r1bq1rk1/1ppn1ppp/p2b1n2/3pp3/8/3P1NPP/PPPNPPB1/R1BQ1RK1 w - -

Now it is very possible that I have missed something, as I couldn't follow the discussions in the last few weeks which lead to the creation of the new book, so basically I am just curious to know if everything is normal here :-)

Thanks for the hard work, BTW :-)

**Comment by vondele** [comment]
@snicolet the condition is 'and', but the key is `using the position at ply 8 for those games where the position at ply 12 is blocked`, so this is 4 plies before the condition is actually satisfied. So, it is not yet necessarily blocked, for the fen put in the book, but SF, when playing 4 more plies arrived in a blocked position in that game for that fen....

**Comment by snicolet** [comment]
Oh, I see, smart!

**Pull request merged**
