### PR TITLE
Book with positions according to frequency

### PR DESCRIPTION
**Pull request by vondele**
* games played on lichess (lichess_db_standard_rated_2020-01.pgn)
* TC > 60s and WhiteELo > 1800 and BlackElo > 1800 (8917954 games)
* FENs in all games ordered wrt (approximate) frequency (games analyzed to the first 'novelty' only)

The book contains 200000 positions.

### CODE REVIEW

**Comment by xoto10** [comment]
So this is 200,000 unique positions, is that right?

Do you have some rough info on the distribution of lengths from startpos? I guess startpos once, a few 1-ply positions, (a few)^2 2-ply posiitons, etc ? Perhaps I've answered that one myself :)

**Comment by vondele** [comment]
@xoto10 yes, the 200k unique most frequent positions. The epd has them in the order of frequency.

I didn't collect the plies from startpos info, but your idea is roughly right, I think, with the exception of some very long popular lines that will be there much more than the simple scheme suggests.

**Comment by vondele** [comment]
@xoto10 BTW, this is from lichess games, but it would be trivial to do that for any other public pgn database. You did post the link to lczero games, I had a quick look, but how can we pick good-quality games... some of the pgn's were clearly from the early phase (like mate in 8 from startpos).

**Comment by xoto10** [comment]
> ... You did post the link to lczero games, I had a quick look, but how can we pick good-quality games... some of the pgn's were clearly from the early phase (like mate in 8 from startpos).

Ah, I didn't know, I'm not familiar with their project. I think it mentioned "matches" so I thought they might be better games.

**Pull request merged**
