### PR TITLE
add cutechess-cli-64 for macos

### PR DESCRIPTION
**Pull request by RaimundHeid**
Successfully checked with VirusTotal.

### CODE REVIEW

**Comment by RaimundHeid** [comment]
@ppigazzini I have added the script that was used for the new binary to https://github.com/glinscott/fishtest/wiki/Build-cutechess-with-Qt5-static.

**Comment by ppigazzini** [comment]
Nice!
I added in the linux/win zip also the `COPYING` file, not an open source license expert, though.
I'm wondering why the MacOS wiki script runs `make` with only 1 job (thread), the Qt5 static build should keep running forever :)

**Comment by RaimundHeid** [comment]
> Nice! I added in the linux/win zip also the `COPYING` file, not an open source license expert, though. I'm wondering why the MacOS wiki script runs `make` with only 1 job (thread), the Qt5 static build should keep running forever :)

I looked into the zip man page in order to understand what the effect of COPYING could be :) - added now.

I ran the script on a MacBook Air 2018 with a 2-core i5 cpu. Two threads would have killed the fan, I suppose :)

**Comment by vondele** [comment]
> I looked into the zip man page in order to understand what the effect of COPYING could be :) - added now.

can you push that updated zip, ideally squashing all your commits in a single one.

**Comment by RaimundHeid** [comment]
Something went wrong while squashing. Take the new PR, please.

**Pull request closed without merging**
